- hosts: terraform-ansible
  tasks:
    - name: criando arquivo index.html
      ansible.builtin.copy:
        dest: /home/ubuntu/index.html
        content: "<h1>Hello World with ansible and terraform</h1>"
      
    - name: criando servidor
      ansible.builtin.shell: nohup busybox httpd -f -p 8080 &
